### ISSUE TITLE
IDEA: Add READ ME in the issues tab, like what jod did. Yk what I mean.

### ISSUE THREAD

**Issue by otmfyourandomize** [05Konz/Blooket-Cheats#1]
### Gamemode

All

### Function

To help people know. Yeeeeee, and they’re no FaQ lol.

### FaQ

I have not read the FaQ

**Comment by 05Konz** [comment]
?
I don't understand what you mean, the FaQ can still be found in the [readme](https://github.com/05Konz/Blooket-Cheats/blob/main/README.md)

**Comment by otmfyourandomize** [comment]
True... but shouldnt it be also here?
