### ISSUE TITLE
IDEA: give user control for the bots

### ISSUE THREAD

**Issue by DoxrGitHub** [05Konz/Blooket-Cheats#101]
erekcvroijoire

redacted

**Comment by 05Konz** [comment]
https://github.com/05Konz/Blooket-Cheats/blob/main/cheats/global/floodGame.js
On line 33 that has ``let ign = `${name}${Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2)}`;`` just replace it with `let ign = "any name" + i;`
