### ISSUE TITLE
IDEA: join game late

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#102]
### Gamemode

Global

### Function

Allows you to join a game late even if late joins are off

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Mazedotexe** [comment]
bro i swear when will you learn what things are obviously not possible

just think in your head for a second.

**Comment by Githubman6996** [comment]
> bro i swear when will you learn what things are obviously not possible
> 
> 
> 
> just think in your head for a second.

I'm absolute shit at coding I don't know most crap that's not possible besides stuff like coins and permanent blooks
