### ISSUE TITLE
Question: What do you do after making the bookmark folders?

### ISSUE THREAD

**Issue by PIX3LED** [05Konz/Blooket-Cheats#103]
### Script

Bookmarklets.html

### Problem

They are all empty for me. It may be bc I'm on a school laptop but, idk.

### Method

Imported Bookmarklets.html

### Type

Unobfuscated

### Extra Info

![Capture](https://github.com/05Konz/Blooket-Cheats/assets/157727160/d3e3b1ec-3c0d-48f7-a752-29d36c5f5b5e)

**Comment by ASTHEBEST** [comment]
try it again, worked for me. if it doesn't work try using a normal computer, importing the bookmarks and syncing them over to the school laptop.(if you have one)

**Comment by ASTHEBEST** [comment]
also you asked how to use get daily rewards, go to play.blooket.com, and enter the code(bookmarklet or console)

**Comment by 05Konz** [comment]
Pretty sure this is caused by the school computer
