### ISSUE TITLE
BUG: reset all gold

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#104]
### Script

cheats/gold/resetAllGold.js

### Problem

It’s very laggy and I’m pretty sure broken 

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated, Obfuscated

**Comment by 05Konz** [comment]
You can only swap gold with one person at a time, and swaps are only processed every 4 seconds

**Comment by Githubman6996** [comment]
> You can only swap gold with one person at a time, and swaps are only processed every 4 seconds

Oh ok
