### ISSUE TITLE
IDEA: set questions 

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#105]
### Gamemode

Racing

### Function

Sets the question number your on

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by CryptoDude3** [comment]
I already wrote a script for this, here it is:
```
javascript:var iframe = document.createElement("iframe");document.body.appendChild(iframe);window.prompt=iframe.contentWindow.prompt.bind(window);window.alert=iframe.contentWindow.alert.bind(window);iframe.remove();function reactHandler(){return Object.values(document.querySelector('body div[class*="camelCase"]'))[1].children[0]._owner}reactHandler().stateNode.props.liveGameController.getDatabaseVal("s",e=>{let questions = e.a; let newpos = questions-parseInt(prompt("Enter number of questions left: "));if(Number.isNaN(newpos)){alert("You must enter a number!");return;}reactHandler().stateNode.props.liveGameController.setVal({path:"c/" + reactHandler().stateNode.props.client.name,val:{b:reactHandler().stateNode.props.client.blook,pr:newpos}});reactHandler().stateNode.setState({progress:newpos});});
```

**Comment by Githubman6996** [comment]
> I already wrote a script for this, here it is:
> 
> ```
> 
> javascript:var iframe = document.createElement("iframe");document.body.appendChild(iframe);window.prompt=iframe.contentWindow.prompt.bind(window);window.alert=iframe.contentWindow.alert.bind(window);iframe.remove();function reactHandler(){return Object.values(document.querySelector('body div[class*="camelCase"]'))[1].children[0]._owner}reactHandler().stateNode.props.liveGameController.getDatabaseVal("s",e=>{let questions = e.a; let newpos = questions-parseInt(prompt("Enter number of questions left: "));if(Number.isNaN(newpos)){alert("You must enter a number!");return;}reactHandler().stateNode.props.liveGameController.setVal({path:"c/" + reactHandler().stateNode.props.client.name,val:{b:reactHandler().stateNode.props.client.blook,pr:newpos}});reactHandler().stateNode.setState({progress:newpos});});
> 
> ```

Ty

**Comment by Githubman6996** [comment]
Konz should honestly make this a script

**Comment by 05Konz** [comment]
ok
