### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#11]
### Gamemode

Pirates voyage

### Function

Can you make pirates voyage hacks 

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by SorkoPiko** [comment]
![image](https://github.com/05Konz/Blooket-Cheats/assets/36188446/16b828f3-94ec-46f7-91b1-a20b1c9d0287)
