### ISSUE TITLE
BUG: Mobile GUI not working at all

### ISSUE THREAD

**Issue by BlooketGodFr** [05Konz/Blooket-Cheats#110]
### Script

Mobilegui.js

### Problem

Not working at all no gui shows

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

### Extra Info

No working pls test it ur self

**Comment by TheDarknessSurroundsYou** [comment]
Recopy the script! it stops working when it is outdated.
