### ISSUE TITLE
BUG: mobileGui.min.js not working at all.

### ISSUE THREAD

**Issue by SoggyPineapple** [05Konz/Blooket-Cheats#111]
### Script

mobileGui.min.js

### Problem

It does not show up on Blooket any more. I know the problem is not me because I re did it 5 times and checked several YouTube videos.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

### Extra Info

![Uploading IMG_0456.jpeg…]()

**Comment by BlooketGodFr** [comment]
Yep Same issue here

**Comment by YourBadik** [comment]
And here

**Comment by microcrit** [comment]
if you're in konz' discord,   
https://discord.com/channels/1143282545727905792/1143284397714460903/1207369805435371600   
   
the update checker broke and a patch is being released

**Comment by 05Konz** [comment]
Fixed
