### ISSUE TITLE
BUG: mobileGui.min.js

### ISSUE THREAD

**Issue by DeckerS190** [05Konz/Blooket-Cheats#113]
### Script

Mobile guy.min.js

### Problem

It was working really good for awhile but stopped working for some reason pls fix it I love your hacks 

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

It worked for awhile but stopped

**Comment by TheDarknessSurroundsYou** [comment]
try recopying the script. it stops working when it is outdated as a fail safe!

**Comment by 05Konz** [comment]
Fixed
