### ISSUE TITLE
BUG: Unlock Plus Game modes

### ISSUE THREAD

**Issue by WildUser100** [05Konz/Blooket-Cheats#12]
### Script

Mobile GUI/ GUI Min and clicking the unlock plus game modes

### Problem

So I was trying to play the prate Voyage game mode but I had no plus. So I thought maybe using the unlock game mode cheat would make it work. It did work and unlocked it but when I clicked host game, it just stopped and didn’t work.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by SorkoPiko** [comment]
![image](https://github.com/05Konz/Blooket-Cheats/assets/36188446/43846747-f796-4582-bae5-951dfb0346a5)
