### ISSUE TITLE
BUG: Unlock Plus Gamemodes

### ISSUE THREAD

**Issue by ASTHEBEST** [05Konz/Blooket-Cheats#13]
### Script

unlockPlusGamemodes.js unlockPlusGamemodes.min.js

### Problem

It just crashes when I open any plus gamemodes after using the hack.

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated, Obfuscated

**Comment by SorkoPiko** [comment]
![image](https://github.com/05Konz/Blooket-Cheats/assets/36188446/fa1599de-f453-4708-a8c5-7bdd23a720a5)

**Comment by blooketplay** [comment]
still dont work

**Comment by SorkoPiko** [comment]
did you even read what i sent you? it's PATCHED. that means it doesn't work.
please use you eyes before replying next time.

**Comment by blooketplay** [comment]
Chill out my guy 
Doesn't patched mean that something is fixed, like patching a hole in a shirt?
*your*

**Comment by SorkoPiko** [comment]
patched means ben patched it.
ben fixed it from _his_ perspective. our _patched_ is the opposite of ben's _patched_.
also, due to how this hack works, it is unlikely it will come back.
join the discord for more info.
