### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by WildUser100** [05Konz/Blooket-Cheats#14]
### Script

Pirate Voyage Game mode

### Problem

As how you made the GUI for the pirate voyage, mobile GUI cannot detect the Pirate Voyage game mode. I also have a image of it. 

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

![IMG_6936](https://github.com/05Konz/Blooket-Cheats/assets/142946877/c018be46-446d-4607-8b02-dee488fae689)

**Comment by 05Konz** [comment]
Fixed

**Comment by WildUser100** [comment]
Thanks!
