### ISSUE TITLE
IDEA: Fishing Frenzy

### ISSUE THREAD

**Issue by WildUser100** [05Konz/Blooket-Cheats#15]
### Gamemode

Fishing Frenzy

### Function

In fishing frenzy, there could maybe be a cheat were it lets you fish anything! You just have to write the name of the blook like how you have to in change blook in-game that can be possible to fish out like the Megalodon 

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by WildUser100** [comment]
1.

**Comment by REAL-DEMON** [comment]
i like it

**Comment by WildUser100** [comment]
Thanks

**Comment by blooketplay** [comment]
i said that on minescraft's page, pretty sure not possible tho
said from a coding noobie so 🤷🏾‍♂️

**Comment by XOTlC** [comment]
I think it's possible I don't remember how fishing frenzy fishes up the blooks but you could change the blook fished up

**Comment by WildUser100** [comment]
I thought of this because lots of my friends catch extremely rare things up in fishing frenzy and I thought I can just write in the name for it to be possible.

**Comment by ASTHEBEST** [comment]
just set lure to 5 and you will basically always get good blooks.

**Comment by 05Konz** [comment]
It'd be an insanely tedious script to make when you can just set your lure to max level
