### ISSUE TITLE
IDEA: Script idea name

### ISSUE THREAD

**Issue by REAL-DEMON** [05Konz/Blooket-Cheats#16]
### Gamemode

battle royal

### Function

in battle royal, you could make a cheat that allows you to pick the next person your going to fight by their user name.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by WildUser100** [comment]
Good idea

**Comment by 05Konz** [comment]
not possible

**Comment by WildUser100** [comment]
Oh

**Comment by WildUser100** [comment]
Hi Konz
