### ISSUE TITLE
IDEA: Script idea name

### ISSUE THREAD

**Issue by REAL-DEMON** [05Konz/Blooket-Cheats#17]
### Gamemode

global

### Function

if this is possbile could you make a script that changes your username and ammount of points you have but only on your screen so if some kid comes around to check if your the one cheating then it will appear as tho not. you can add additional settings and things to this if you wanted. does it make sence?

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by SorkoPiko** [comment]
idk how blooket works as much as @05Konz but im sure you could do that.
would be a matter of changing the html and sending a different score to the server.
idk how hard/easy that would be but it should be doable

**Comment by REAL-DEMON** [comment]
in edition, once exected is it possible to make the score change how it normally would, so for example if you executed it and you then got a megladon, you would still get the megalodon points on your screen and on the server so if people aksed to see then it would  look like your legit. second, if you were to change the score again by using cheats then the score on your screen would not change but the server score would. 
**these are ideas so if they are not possible then ingore this.**

**Comment by PIX3LED** [comment]
I just want to use the daily rewards hacks, but I don't really know how is works... Anybody able to help? (Comment on the "Question:..." post I made!) :) thx
