### ISSUE TITLE
IDEA: Improve readme and add link to github within cheat

### ISSUE THREAD

**Issue by pazza2234** [05Konz/Blooket-Cheats#19]
### Function

This is a exstreamly short list of things I would like to see added. Please and Thanks.

1. Can you improve readme to add instructions for the PNG cheats and copy/paste the discripions for the hacks found by hovoring over the cheats into the readme.

2. in the top right of the cheat menu it has the text ``` GitHub - 05Konz ``` and for updating porpuses that should be a hyperlink to the github here. You could also have it redirect here when the cheats detect they are outdated.

3. When creating a issue, it request's that you read the FaQ. but that gose to Minecraft2's page witch has been taken down. Can you either restore or remove that?

These are just sugestions that I would like to see added to the blooket cheats for both polish and ease of use.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 05Konz** [comment]
I did 2 and 3, but to be entirely honest there's no solid way to use the autoupdate scripts without a CSP bypass and you can't really make a tutorial for that since it would only work on personal computers. Also, what do you mean "found by hovoring over the cheats into the readme." They're not in the readme

**Comment by pazza2234** [comment]
@05Konz in the gui, when you hovor over some of the cheats it gives a small saying on what the cheat dose.

sorry for the lait responce and thank you.

have a good day

**Comment by Qwwhuhdeyudgh** [comment]
*late* not lait
get rekt bozo

**Comment by 05Konz** [comment]
Not really gonna bother putting the descriptions into the readme since you can find them in the readmes for each folder
