### ISSUE TITLE
Dragging Tool

### ISSUE THREAD

**Issue by CarsonCheats** [05Konz/Blooket-Cheats#2]
### Gamemode

Every

### Function

**Im recommending a page to drag scripts into bookmarks for safari, as it was on the old site and the page shouldn’t be too hard to make, as the code is available.**

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 05Konz** [comment]
[05konz.github.io/Blooket-Cheats/](https://05konz.github.io/Blooket-Cheats/)
