### ISSUE TITLE
Help: How to use PNG

### ISSUE THREAD

**Issue by pazza2234** [05Konz/Blooket-Cheats#24]
### Gamemode

All, mainly the gui

### Function

ok I do not know if I am stupid but in the tutorial can you tell us how to use the png's to use gui?

**Comment by ASTHEBEST** [comment]
what do you mean?

**Comment by pazza2234** [comment]
if you go into autoupdate there us gui.png. how do I go from that file (gui.png) to blooket cheats?

**Comment by RipAngelhacks** [comment]
> if you go into autoupdate there us gui.png. how do I go from that file (gui.png) to blooket cheats?

dont use that go to cheats then use gui.js if u dont know how to run the code make a bookmark then put javascript: 
then paste the code

**Comment by goldenscyth** [comment]
How to javascript ?

**Comment by 05Konz** [comment]
That's for the auto update bookmarklets.html file, which can only be used with a CSP unblocker. It's best to use the normal ones unless you know what you're doing,
