### ISSUE TITLE
BUG: Simulate Unlock(pirate pufferfish opens in aquatic pack.)

### ISSUE THREAD

**Issue by ASTHEBEST** [05Konz/Blooket-Cheats#25]
### Script

SimulateUnlock.js SimulateUnlock.min.js

### Problem

Pirate Pufferfish opens in aquatic pack instead of pirate pack.

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated, Obfuscated

**Comment by capricec13** [comment]
I'm stupid but what's the point of having the simulate unlock when you don't actually get the blook? Sorry, I just don't understand could soeone please explain?

**Comment by ASTHEBEST** [comment]
its to brag or smt

**Comment by 05Konz** [comment]
Can't really do much about that, since all that's put in is the blook, not which pack it comes from. The fact that it shows the aquatic background is actually pretty surprising
