### ISSUE TITLE
Remove the "Would you like to alert blooks upon unlocking?" page

### ISSUE THREAD

**Issue by Pop1224** [05Konz/Blooket-Cheats#27]
### Gamemode

Market

### Function

The Auto box opener is the same, but without the "Would you like to alert blooks upon unlocking?" page. This would be really helpful, and make using the hack faster.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by bcrhbrhcdb** [comment]
Dont, It help with Pity luck. You will get more legendaries and good blooks

**Comment by blooketplay** [comment]
use the hack or the alert

bc i feel like the auto opener gives you trash stuff

**Comment by Shploop** [comment]
Here’s a suggestion for y’all (Including @05Konz) could you make it so its “Yes” “No” and “Cancel” cuz its rlly annoying clicking the screen.

**Comment by Pop1224** [comment]
I agree with that, clicking the screen is annoying. @Shploop

**Comment by 05Konz** [comment]
The option is given to you so you can refresh and stop the script when you get your target blook, and it's honestly not even that bad pressing a singular extra button when bulk opening.
I'll move it to be a dropdown input for the GUI and React GUI, anymore and I'd be removing features.
