### ISSUE TITLE
IDEA: HOW TO GET ON MOBILE. I FIGURED IT OUT.

### ISSUE THREAD

**Issue by Shploop** [05Konz/Blooket-Cheats#35]
### Gamemode

Mobile GUI

### Function

You go to the right top and click on the 05Konz GitHub.io link and scroll down in global and drag the gui into your bookmarks then it should work! 

Your welcome!

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 05Konz** [comment]
good job, add the video and I'll pin it

**Comment by Shploop** [comment]
Kk

**Comment by Shploop** [comment]
Could i send it to u on discord idk how to put it on here.

**Comment by victini-fan** [comment]
this doesnt work for me
I am an a ASUS google Chromebook (not a school Chromebook)
