### ISSUE TITLE
BUG: CHANCE OF SUSPENSION **VERY IMPORTANT PLEASE READ**

### ISSUE THREAD

**Issue by Shploop** [05Konz/Blooket-Cheats#36]
### Script

CHANCE OF SUSPENSION

### Problem

I was regularly trolling blooket streamers with the hacks and all of the sudden I got banned! Im starting to run out of emails and I need Blooket for School! Right now im using a fake email but please fix immediately! Thank you.

Try making it more hidden/deeper in the code so it is less traceable.

Also, is there any way you could make a free premium for free?

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

Please fix immediately!

**Comment by ASTHEBEST** [comment]
Also, is there any way you could make a free premium for free?
Well no. It used to exist but got patched.

**Comment by Shploop** [comment]
Ik its my 4th alt 💀

**Comment by 05Konz** [comment]
Just sign out when flooding games, I'm not sure what to do about this.
