### ISSUE TITLE
IDEA: Host Plus/Unobtainable Gamemodes

### ISSUE THREAD

**Issue by bensimms1** [05Konz/Blooket-Cheats#37]
### Gamemode

Toy, Pirate

### Function

Lets you host plus-only, or unobtainable gamemodes.
Here is the gui(goes under global array in gui script):
```                 
{
                    name: "Host Custom Gamemode",
                    description: "Hosts a custom gamemode with the gamemode(plus or hidden) of your choice.",
		    inputs: [{
                            name: "Game",
                            type: "options",
                            options: function(){return ["Toy","Pirate"];}
                        }],
                    run: function (gm) {
                        const { stateNode } = Object.values((function react(r = document.querySelector("body>div")) { return Object.values(r)[1]?.children?.[0]?._owner.stateNode ? r : react(r.querySelector(":scope>div")) })())[1].children[0]._owner;
                        stateNode.state.settings.type = gm;
			stateNode.forceUpdate();
                    }
                }
```
Must be on the host options screen:
![hostscreen](https://github.com/05Konz/Blooket-Cheats/assets/66845757/3d9ac948-122c-4b79-8bc7-d95883d4df00)

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Githubman6996** [comment]
Good idea

**Comment by ASTHEBEST** [comment]
This cheat used to be added but got patched. Probabaly no.

**Comment by bensimms1** [comment]
I thought it was patched, but I tried this code 3 days ago and it still works

**Comment by Shploop** [comment]
Hold up, I’ve never seen 05Konz respond to a comment xD

**Comment by Iamtotally-yourfather** [comment]
i dont know if this was mentioned already but when I try using all blooks it dosent save it just dissappears when i go to join a game..

**Comment by guhiclell** [comment]
> i dont know if this was mentioned already but when I try using all blooks it dosent save it just dissappears when i go to join a game..

You only use it in the lobby of a game, enter game ID, use the cheat and select your blook.

**Comment by Shploop** [comment]
Chop chop @05Konz its nighttime rn

**Comment by 05Konz** [comment]
> Chop chop @05Konz its nighttime rn

source?

**Comment by guhiclell** [comment]
His timezone

**Comment by Shploop** [comment]
Chop chop hacker boy its been 2 days

**Comment by 05Konz** [comment]
I don't have the freetime remind me in 11 hours when I wake up

**Comment by Githubman6996** [comment]
> i'll make something in the morning

You gonna make it

**Comment by Shploop** [comment]
Thank you. How fast do you code??? Jesus.

**Comment by 05Konz** [comment]
> Thank you. How fast do you code??? Jesus.

give me like, 3-5 business days to start

**Comment by 05Konz** [comment]
my life is much more busier than jod's

**Comment by Shploop** [comment]
Lol
