### ISSUE TITLE
IDEA: The Correct Answer is always in the top left corner so it looks like your not hacking.

### ISSUE THREAD

**Issue by Shploop** [05Konz/Blooket-Cheats#38]
### Gamemode

Global

### Function

It puts the correct answer in the top left corner so it looks like your not hacking. @05Konz @05Konz plss

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Shploop** [comment]
@05Konz plssss add this

**Comment by Shploop** [comment]
@05Konz @05Konz @ZammyDog @ZammyDog @05Konz plss add

**Comment by 05Konz** [comment]
Would be hard to figure out where to hide it, so instead I removed the shadows from correct answers. [subtleHighlightAnswers.js](https://github.com/05Konz/Blooket-Cheats/blob/main/cheats/global/subtleHighlightAnswers.js)

**Comment by Shploop** [comment]
Ty
