### ISSUE TITLE
Help:Javascript dont work

### ISSUE THREAD

**Issue by goldenscyth** [05Konz/Blooket-Cheats#39]
When i javascript the gui.js and even modify it the gui doesnt popup and just doesnt do anything so can i please get a tutorial or some help

**Comment by Shploop** [comment]
Go to my issue on how to get on mobile.

**Comment by 05Konz** [comment]
If you're on a school computer javascript is probably blocked, if not how exactly are you running the gui?

**Comment by goldenscyth** [comment]
Copy raw code minify got to blooket market javascript:(pastecode) and
nothing happens

**Comment by goldenscyth** [comment]
I copy the raw code minify it go to the blooket market page search bar i
type javascript:(paste the code)

**Comment by goldenscyth** [comment]
Shploop could put a video as a tutorial ?

**Comment by LILPR09** [comment]
HI I CREATED A DISCORD ACCOUNT

**Comment by Shploop** [comment]
@goldenscyth I have a tiktok I posted a tutorial there. Its @TheRealShploop

**Comment by Shploop** [comment]
Or you could give me your discord and I can send you the video.

**Comment by theturtleking137** [comment]
i copyed the daly rewards js.are you MAD?05konz

**Comment by Shploop** [comment]
He wont care as long as you give credit.

**Comment by 05Konz** [comment]
> He wont care as long as you give credit.

I'm not a dude

**Comment by Shploop** [comment]
Sorry 💀

**Comment by goldenscyth** [comment]
@Shploop my discord is golden_scyth 
what is the user that i must expect ?
