### ISSUE TITLE
IDEA: Script idea name

### ISSUE THREAD

**Issue by WildUser100** [05Konz/Blooket-Cheats#4]
### Gamemode

Detective Dinos

### Function

For detective Dino’s, if possible, try adding a script that you can cheat and see through the rocks but if the other players try to investigate you, it would say clear instead of cheater.

### FaQ

I have read the FaQ

**Comment by SorkoPiko** [comment]
already a thing, it's called rockESP: https://github.com/05Konz/Blooket-Cheats/blob/main/cheats/dinos/rockESP.min.js
