### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by KittenPixel-cell** [05Konz/Blooket-Cheats#41]
### Script

All Scripts

### Problem

When I run the gui or other scripts it gives this:

```VM222:1 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://play.blooket.com https://fb.blooket.com https://ac.blooket.com https://s.blooket.com https://blooket.s3.us-east-2.amazonaws.com https://kit.fontawesome.com https://*.firebaseio.com https://apis.google.com https://js.stripe.com". at img.onload (<anonymous>:1:536)```

### Method

Imported Bookmarklets.html

### Type

Obfuscated

**Comment by 05Konz** [comment]
Use the ones in the cheats folder, not the autoupdate folder.

**Comment by KittenPixel-cell** [comment]
ah ok
