### ISSUE TITLE
Could you make gimkit hacks?

### ISSUE THREAD

**Issue by Shploop** [05Konz/Blooket-Cheats#42]
### Gamemode

Gimkit

### Function

You make these hacks so good, could you try making a gui or answer bot for gimkit in JavaScript? It’s probably not too different. Thanks!

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

@05Konz

**Comment by Shploop** [comment]
God damn you did that fast.. but why not?

**Comment by 05Konz** [comment]
It's 5:30 in the morning I'm not gonna start working on a near impossible task

**Comment by Shploop** [comment]
Sheeeeesh our time zones are very different WHY ARE YOU AWAKE AT 5:30

**Comment by 05Konz** [comment]
why are you emailing me at 5:30

**Comment by Shploop** [comment]
oops
