### ISSUE TITLE
BUG: Incorrectly Placed Scripts

### ISSUE THREAD

**Issue by Shploop** [05Konz/Blooket-Cheats#43]
### Script

mobileGui.js and reactGui.js

### Problem

In 05Konz.github.io the two are switched around when u drag react gui it is mobile gui and when you drag mobile gui it is react gui.

### Method

Other (described in Extra Info section)

### Type

Unobfuscated

### Extra Info

On 05Konz.github.io dragging the bookmark.

**Comment by 05Konz** [comment]
Can't reproduce
