### ISSUE TITLE
it says page not avalible

### ISSUE THREAD

**Issue by theturtleking137** [05Konz/Blooket-Cheats#44]
### Script

idk

### Problem

c

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

f

**Comment by theturtleking137** [comment]
fr

**Comment by Shploop** [comment]
Wdym page not available? Give more description and I can probably help.

**Comment by 05Konz** [comment]
not enough info provided
