### ISSUE TITLE
IDEA: Load Custom Scripts

### ISSUE THREAD

**Issue by hecker7734** [05Konz/Blooket-Cheats#45]
### Gamemode

Any

### Function

You can make a button to allow users to run/intergrate other scripts "published" by others, this of course will prompt a warning ( maybe you could store the script in a config file or cookie to retrieve it) 

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Githubman6996** [comment]
Good idea

**Comment by 05Konz** [comment]
Content Security Policy blocks all methods to run scripts from strings. If this wasn't the case bookmarklets would only be a line long.
You'd might aswell put the code into tampermonkey or something
