### ISSUE TITLE
IDEA: Make flood game hack autofill the game id when already in lobby of a game

### ISSUE THREAD

**Issue by CryptoDude3** [05Konz/Blooket-Cheats#52]
### Gamemode

Flood Game

### Function

When in the lobby of a game, if you don't know the code or don't want to look at the host's screen again, it will have the game code already filled in the blank.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 05Konz** [comment]
You would get suspended if you're logged in, and you would have to run a script to make it flood the game anyway, no point making it automatic
