### ISSUE TITLE
IDEA: Spam Unlock Blooks Until

### ISSUE THREAD

**Issue by ParticleEddie** [05Konz/Blooket-Cheats#53]
### Gamemode

Market

### Function

It works exactly the same as Spam Unlock Blooks, except the user can select a blook that they would like to collect. The hack will continuously buy blooks until it unboxes the desired blook. Once the chosen blook has been aquired the script ends.

### FaQ

I have not read the FaQ, I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Githubman6996** [comment]
Nah just make it choose any Blook out of a pack

**Comment by 05Konz** [comment]
bruh

**Comment by Warrior1711** [comment]
I would actually quite like to see that, as lets say you want a certain blook it will spam buy until you get it. (or until you run  out of coins)

**Comment by 05Konz** [comment]
God damn how many blook opening/selling scripts do you guys need
