### ISSUE TITLE
IDEA: Kick all players in a game

### ISSUE THREAD

**Issue by Warrior1711** [05Konz/Blooket-Cheats#58]
### Gamemode

Any

### Function

If you paste in the script it will kick all the players.
Don't know if you should yourself or not.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Qwwhuhdeyudgh** [comment]
how would that work? to do that you would have to be the host of the game and unless you can become host it would be impossible

**Comment by 05Konz** [comment]
Only possible on hosts end
