### ISSUE TITLE
IDEA: better auto answer AND spoof win

### ISSUE THREAD

**Issue by Qwwhuhdeyudgh** [05Konz/Blooket-Cheats#63]
### Gamemode

questions AND leader board

### Function

**Better auto answer**
it makes it so you can choose the rate of how fast it answers questions (to avoid suspicion) (ex: 3 seconds to answer it)
it can also choose the percent of times you get it right (to avoid suspicion) (ex: 75% chance to get it correct)

**Spoof win**
says it in its name
it work by adding how much point you need to be what ever place you want last second
there is also two modes additive and percentage
additive adds how much you need to be (place) (ex: 1000 points higher then 3rd place) 
percentage adds how much you need to be (place) by percent (ex: 10% higher then 3rd place)
also if your number (additive or percentage) is higher then what place you want to be it just lowers the number by one

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 05Konz** [comment]
Can't do much for spoof win
