### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by niforru** [05Konz/Blooket-Cheats#64]
Your license prohibits forks and pretty much any other open source activities, this may not feel like a problem but will likely hinder advancements as you have to give explicit permission for almost any activity. If what you want is recognition for code something gpl compatible is likely what you're looking for. 

Nice project though anyway, and best of luck.

**Comment by Qwwhuhdeyudgh** [comment]
yeah it probally wont be a problem for MOST people

**Comment by niforru** [comment]
Still this hinders development and would probably be better to have a better license

**Comment by 05Konz** [comment]
The license was designed and is intended to be restrictive. Any changes and additions can be suggested or added by those who manage the project.
