### ISSUE TITLE
IDEA: Blacket GUI

### ISSUE THREAD

**Issue by Shploop** [05Konz/Blooket-Cheats#67]
### Gamemode

Blacket

### Function

Its blacket.org. Basically blooket. It would be greatly appreciated!

@

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 05Konz** [comment]
Why are you asking again

**Comment by Shploop** [comment]
Oh, whoops I didnt see that you closed it.

**Comment by Shploop** [comment]
It's probably worse coded than blooket, so you could probably make 1 hack that unboxes the blook you put in and you would actually get it.
