### ISSUE TITLE
IDEA: save configuration

### ISSUE THREAD

**Issue by 05KonzFan** [05Konz/Blooket-Cheats#69]
### Gamemode

Gui and React gui

### Function

so, it saves all functions which were turned on, themes of background, size, keybinds  In file, so you can turn the same settings very quickly and teachers wont see how you are setting  up Gui .

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 05Konz** [comment]
Everything in the settings tab _should_ be saving automatically. Are you clearing your localStorage?
