### ISSUE TITLE
getDailyRewards.min question

### ISSUE THREAD

**Issue by DoorsFan1234** [05Konz/Blooket-Cheats#7]
Hey Konz! Im just here to ask, what does getDailyRewards.min mean? Idk whats changed between that and the other daily rewards hack. Do you get daily rewards every minute or something? That would be pretty op lol

**Comment by emperortrademark999** [comment]
it just gives you the maximum amount of daily coins and points. doesn't change the value or give you it every minute.

**Comment by 05Konz** [comment]
.min files replaced the "obfuscated" folder from Jod's original cheats, the file is the exact same just condensed into one line
