### ISSUE TITLE
BUG: kingdom choiceESPLoop.js 

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#72]
### Script

kingdom choiceESPLoop.js 

### Problem

Not working

### Method

Other (described in Extra Info section)

### Type

Obfuscated

### Extra Info

It’s not working on the gui 

I’m using react gui

**Comment by 05Konz** [comment]
I'm not having any issues

**Comment by Githubman6996** [comment]
Sorry its me being fucking stupid

**Comment by Githubman6996** [comment]
I was using an older script
