### ISSUE TITLE
Not Fair

### ISSUE THREAD

**Issue by qwertyA1000** [05Konz/Blooket-Cheats#82]
These cheats are causing lots of trouble in class, fights and yelling. Put them to an end now!

**Comment by 05Konz** [comment]
Sounds like a skill issue to me

**Comment by Warrior1711** [comment]
> Sounds like a skill issue to me

Agreed

**Comment by Githubman6996** [comment]
> Sounds like a skill issue to me

Fr

**Comment by microcrit** [comment]
> These cheats are causing lots of trouble in class, fights and yelling. Put them to an end now!

womp womp

**Comment by Githubman6996** [comment]
> > These cheats are causing lots of trouble in class, fights and yelling. Put them to an end now!
> 
> womp womp

Womp
