### ISSUE TITLE
Simple question on the setVal function

### ISSUE THREAD

**Issue by Zhlonk** [05Konz/Blooket-Cheats#86]
### Gamemode

any

### Function

I’m using this suggestion page to just ask a question, but how did you find all the paths to that setVal function and figure out the correct values/keys in the val: {} part of each path (tat, b, p, etc.)? I’m somewhat new to programming in general so it might be some super easy thing i’m just overlooking, but either way i’d love if you’re able to tell me!

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by 05Konz** [comment]
reading source code
