### ISSUE TITLE
BUG: stimulate unlock

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#87]
### Script

Stimulateunlock.js

### Problem

When some blooks are selected using the gui or just actual stimulate unlock script it won’t work but some will work for example the yeti from the ice monster pack won't work 

### Method

Other (described in Extra Info section)

### Type

Unobfuscated, Obfuscated

**Comment by Mazedotexe** [comment]
Ah yes, “**stimulate unlock ** 💀

**Comment by Mazedotexe** [comment]
Ah yes, **stimulate unlock** 💀

**Comment by Githubman6996** [comment]
Fr💀

**Comment by Chavin10299** [comment]
Help me the cheats don't work anymore!

**Comment by YourBadik** [comment]
> Help me the cheats don't work anymore!

Same here

**Comment by CryptoDude3** [comment]
none of the minified scripts work at the moment, I found a fix for it, you can read my issue abt it, but for now you can just replace the line at the very end of the script that reads:
`/LastUpdated: (.+?); ErrorMessage: "([sS]+?)"/`
with this:
`new RegExp('LastUpdated: (.+?); ErrorMessage: "([\\s\\S]+?)"');`
when the mod is finished it looks like:
`o.match(new RegExp('LastUpdated: (.+?); ErrorMessage: "([\\s\\S]+?)"'));`
