### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#9]
### Gamemode

 Please fix them so I can hack again

### Function

I typed JavaScript; on multiple hacks and they didn’t work 

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by notxivyy** [comment]
nope i used them 5 mins ago lmfao

**Comment by 0-uh** [comment]
blooket cheats aren't working

**Comment by 05Konz** [comment]
I'll fix whatevers broken in the morning

**Comment by Githubman6996** [comment]
Thanks

**Comment by CarsonCheats** [comment]
Ngl to you it’s javascript: not ;
