### ISSUE TITLE
Get Specific/All Blooks

### ISSUE THREAD

**Issue by peno619** [05Konz/Blooket-Cheats#9]
### Gamemode

Global

### Function

so theres one that gives you all the blooks (i dont reccomend) and then theres one where you can get a specific blook, like a rainbow panda. To use it you could just enter "Rainbow Panda" (not "rainbow panda")

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by peno619** [comment]
i think this would be so cool because i like this

**Comment by 05Konz** [comment]
cope
