### ISSUE TITLE
BUG: startHeist.js

### ISSUE THREAD

**Issue by elGato8** [05Konz/Blooket-Cheats#94]
### Script

startHeist.js

### Problem

Can only start heists on myself for some reason

### Method

Imported Bookmarklets.html

### Type

Unobfuscated

**Comment by ASTHEBEST** [comment]
same here

**Comment by CryptoDude3** [comment]
I just fixed the code:
 `javascript:let i = document.createElement('iframe');
        document.body.append(i);
        window.prompt = i.contentWindow.prompt.bind(window);
        i.remove();
        let { stateNode } = Object.values((function react(r = document.querySelector("body>div")) { return Object.values(r)[1]?.children?.[0]?._owner.stateNode ? r : react(r.querySelector(":scope>div")) })())[1].children[0]._owner;
        
        stateNode.props.liveGameController.getDatabaseVal("c", function (val) {
            const players = Object.entries(e || {}).reduce((a, [name, c]) => (a.push({ name, blook: c.b, doubloons: c.d || 0 }), a), []);
            if (players.length === 0) {
                stateNode.questionsToAnswer = 1;
                return void stateNode.randomQ();
            }
            var heist = prompt("Who would you like to heist? (Defaults to top player if no one found)")
            const { name, blook, doubloons } = players.find(x => x.name == heist) || players.sort((a, b) => b.doubloons - a.doubloons)[0];
            stateNode.setState({
                stage: "heist",
                heistInfo: { name, blook },
                prizeAmount: Math.max(1000, doubloons)
            });
        });`
for some reason, the code intentionally only returned the result for one player. it checked for if the name of the player was the same as your name. It looked as if the code was written to make heists on yourself.

**Comment by 05Konz** [comment]
fixed

**Comment by 05Konz** [comment]
i think
