### ISSUE TITLE
BUG: hostAnyGamemode.js

### ISSUE THREAD

**Issue by Githubman6996** [05Konz/Blooket-Cheats#97]
### Script

hostAnyGamemode.js

### Problem

When i host candy quest it shows up as gold quest

### Method

Other (described in Extra Info section)

### Type

Unobfuscated, Obfuscated

### Extra Info

When ending game it shows on the report as candy quest but when hosting it appears as gold quest

**Comment by 05Konz** [comment]
candy quest is gold quest

**Comment by Githubman6996** [comment]
Why did you delete half the issues without responding

**Comment by 05Konz** [comment]
they were all people not knowing how to run javascript

**Comment by 05Konz** [comment]
or just flat out wrong

**Comment by Githubman6996** [comment]
Ok
